DELETE FROM notifies;
DELETE FROM replies;
DELETE FROM commands;
DELETE FROM pictures;
DELETE FROM sensors;
DELETE FROM missions;

ALTER TABLE notifies AUTO_INCREMENT=1;
ALTER TABLE replies AUTO_INCREMENT=1;
ALTER TABLE commands AUTO_INCREMENT=1;
ALTER TABLE pictures AUTO_INCREMENT=1;
ALTER TABLE sensors AUTO_INCREMENT=1;
ALTER TABLE missions AUTO_INCREMENT=1;
