/*
*  Generated by AN Unibo
*/
package it.unibo.contact.platformuv;
import java.net.Socket;
import it.unibo.is.interfaces.protocols.ITcpConnection;
import it.unibo.is.interfaces.protocols.ITcpInteraction;
import it.unibo.is.interfaces.IOutputView;
import it.unibo.is.interfaces.protocols.IConnInteraction;
import it.unibo.platform.tcp.SocketTcpConnSupport;
import it.unibo.platform.tcp.SocketTcpSupport;
 

public  class TcpOut extends ConnProtOut{ 
protected ITcpConnection supportTcp;
protected ITcpInteraction connection;
	public TcpOut(
			String receiver,String msgId, String sender, IOutputView view) throws Exception{
		super(receiver,  msgId,  sender,   view);
	}

	public IConnInteraction doConnect(  ) throws Exception{		
		//println("connecting to " + hostname + " " + portNum + " of " + receiver + " for " + sender);
		if( connection != null ) return connection;
 
  		supportTcp = new SocketTcpSupport("TcpOut"+sender, view);
		Socket sock = supportTcp.connectAsClient( hostname,portNum );	//bloccante
		connection  = new SocketTcpConnSupport("TcpOut"+sender, sock, view);		  
		println("New connection done as client to " + portNum + " for msgId=" + msgId);
		return connection;		
 	}

 
} 
