/*
*  Generated by AN Unibo
*/
package it.unibo.contact.platformuv;
import it.unibo.is.interfaces.IPolicy;

public class Policy implements IPolicy{
	String mode ;
	public Policy( String mode ){
		this.mode = mode;
	}
	 
	 
	public String getPolicy() {
 		return mode;
	}
}
