/*
*  Generated by AN Unibo
*/
package it.unibo.contact.platformuv;
import java.util.HashMap;
//import org.osgi.framework.BundleContext;
//import org.osgi.framework.ServiceReference;
import it.unibo.is.interfaces.IOutputView;
import it.unibo.is.interfaces.platforms.ILindaLike;
 
public class SupportFactory {
	public static final String connSetMsg ="setConnChannel"; //invitation
 	protected static HashMap<String,ConnProtIn> activePorts = new HashMap<String,ConnProtIn>();
 	private static boolean debug  =
		( System.getProperty("medclTrace") != null ) ?
		debug = System.getProperty("medclTrace").equals("set") : false;
  
	public static ILindaLike createConnOut(
			 String receiver, String msgId, String sender,  IOutputView view) throws Exception{
 throw new Exception("The system has no subject with connection port");
	}

	public static ILindaLike createInSupport(
				String receiver,String msgId, boolean withAnswer,IOutputView view ) throws Exception{
	if( RunTimeKb.worksWith( "TCP", receiver, msgId) ){
	 		//println(view,"createInSupport create a new TCP input for " + receiver+msgId );
		ILindaLike tcpS  = createTCPIn(receiver, msgId, withAnswer,view);
 			return tcpS;				
	}  
		throw new Exception("Protocol unknown");
	}


	public static ILindaLike createOutSupport(
				String receiver,String msgId, String sender, IOutputView view) throws Exception{
	if( RunTimeKb.worksWith( "TCP", receiver, msgId) ){
		println(view,"createOutSupport create a new TCP output support for " + receiver+msgId + " in " + sender);		
		ILindaLike tcpS = SupportFactory.createTCPOut(receiver, msgId, sender,view);
	 		RunTimeKb.addSubjectOutConnSupport(sender, receiver+msgId, tcpS );
		return tcpS;				
	}
		throw new Exception("Protocol unknown");
	} 


    /*
   * TCP
   */ 
  	public static ILindaLike createTCPOut(
  			final String receiver,String msgId,final String sender, final IOutputView view) throws Exception{	
     		ILindaLike sup  = new TcpOut(receiver,msgId,sender,view);
  		return sup;
  	}
  
   	public static synchronized ILindaLike createTCPIn(
  			String receiver, String msgId , boolean withAnswer,IOutputView view) throws Exception{
      	/*
     		* VI E' IL PROBLEMA di withAnswer
     		* Il thread TcpIn non è consapevole dei msgId, ma li apprende dal primo
     		* messaggio ricevuto ad una nuova connessione
     		* Per ogni nuova richiesta di connessione TcpIn crea un oggetto
     		* ConnReceiver che ha il suo proprio msgId e dovrebbe avere anche il suo withAnswer
     		* Poichè ciò non accade i msg con diverso withAnswer deveono avere UN DIVERSO portNum
      		*/  			 
     		int portNum = RunTimeKb.getPortNum(receiver,msgId);
  		if( activePorts.get(""+portNum) == null ){
  	   		println(view,"createNewTCPInSupport for " + receiver+"_"+msgId + " portNum =" + portNum);
    		   	TcpIn tcpR = new TcpIn( receiver, msgId, portNum, withAnswer,view);
   			activePorts.put(""+portNum, tcpR);
  			RunTimeKb.addSubjectInConnSupport(receiver, receiver+msgId, tcpR );
  		 	tcpR.start();
  		}
   		return  LindaLike.getSpace(view);
  	}
  
  /*
  * SERVICES	(Called by ConnProt)
  
   
  	public static IServiceTcp getTcpService( BundleContext context  ){
  		if( context != null ){
  			ServiceReference ref = context.getServiceReference( IServiceTcp.class.getName() );
  			IServiceTcp tcpServ = (IServiceTcp)context.getService(ref);
  			return tcpServ;
  		}			
  		else return new ServiceTcp();
  	}	
  */
	
/*
* UTILS	
*/
	
	protected static void println( IOutputView view, String msg){
		 if( debug ) 
			 doprintln(view,msg);
	}

	protected static void doprintln( IOutputView view, String msg){
		if( view != null )
			view.addOutput("    %%% SupportFactory "+ msg);
		else System.out.println( "    %%% SupportFactory " +  msg  );		
	}

}
