/* ======================================================
* Generated by AN 
* University of Bologna
* ======================================================-
*/
package it.unibo.droneMission.smartDevice.android;
public class ActionCode {
	public static final int notifyReceivedActionCode = 13;
	public static final int startMissionActionCode = 14;
	public static final int updateValuesActionCode = 15;
	public static final int endMissionActionCode = 16;
}//ActionCode
