/*
*  Generated by AN Unibo
*/
package it.unibo.contact.platformuv;
import it.unibo.is.interfaces.IBasicMessage;
import alice.tuprolog.*;

public class BasicMessage implements IBasicMessage{
	protected int msgNum;
	protected Term msg;
	
 	
	public BasicMessage( int msgNum, Term msg ){
		this.msgNum = msgNum;
		this.msg = msg;
	}
	
	public BasicMessage( int msgNum, String msg ) throws Exception{
		this.msgNum = msgNum;
		this.msg = Term.createTerm(msg);		
	}

	public BasicMessage( String msg ) throws Exception{
		Term mmmsg = Term.createTerm(msg);
		Term msgNum = ((Struct) mmmsg).getArg(1);
		this.msgNum = Integer.parseInt(msgNum.toString());
		this.msg = ((Struct) mmmsg).getArg(0);		
	}

	public int getMsgSeqNum(){ 
		return msgNum; 
	}
	
	public String getMsgContent(){ //content=msg( A, N) quindi prendo A
		return  ((Struct) msg).toString();
	}	
	
	public String getMsgName(){
		return  ((Struct) msg).getName();
	}
	
	public Term getTerm(){
		return msg;
	}
	
	public static void main(String[] args) throws Exception{
		BasicMessage bm = new BasicMessage("mmm( a(s , mid , mc , 3), 1 )");
		System.out.println( ""+bm.getMsgSeqNum());
		System.out.println( ""+bm.getMsgContent());
		System.out.println( ""+bm.getMsgName());
		System.out.println( ""+bm.getTerm());
		
		System.out.println(  bm.basicToString() );

	}

	public String basicToString() {
		String ms = "mmm( "+ getMsgContent() + " , " + getMsgSeqNum() + ")"  ;
		return ms;
	}
}
