/*
*  Generated by AN Unibo
*/
package it.unibo.contact.platformuv;
public class ProtocolInfo{
private String protocolName;
private String hostName;
private int portNum;

public ProtocolInfo(String protocolName, String hostName, int portNum ){
	this.protocolName = protocolName;
	this.hostName 	  = hostName;
	this.portNum 	  = portNum;
}

public String getProtocolName(){
	return protocolName;
}

public String getHostName(){
	return hostName;
}

public int getPortNum(){
	return portNum;
}	
}
