/*
*  Generated by AN Unibo
*/
package it.unibo.contact.platformuv;
public class Consts {
	public static final String dspaceAnswer = "dspaceAnswer";
	public static final String tcpBasicJar = "it.unibo.platform.tcp_1.4.0.jar";
}	
