/*
*  Generated by AN Unibo
*/
package it.unibo.contact.platformuv;
import it.unibo.is.interfaces.IPolicy;

public class InteractPolicy  {
 	 
	public static IPolicy booked() {
 		return new Policy("booked");
	}
	public static IPolicy constrained() {
 		return new Policy("protected");
	}	
	public static IPolicy nopolicy() {
 		return new Policy("nopolicy");
	}	
	
} 
