/*
*  Generated by AN Unibo
*/
package it.unibo.contact.platformuv;
import it.unibo.is.interfaces.IOutputView;
import it.unibo.is.interfaces.platforms.ILindaLike;
import it.unibo.is.interfaces.protocols.IConnInteraction;
import java.util.HashMap;
public class RunTimeKb{
	private static HashMap<String,Boolean> inputConnMsg = new HashMap<String,Boolean>();
	private static IOutputView view = null;	
	private static boolean isDistributed = false;
    private static boolean debug = false;
	
	public static void init(IOutputView aview){
		view = aview;
		String debugOn = System.getProperty("medclTrace");
		if( debugOn != null ) {
			debug = debugOn.equals("set") ;
		}
		init();
	}
	
	public static void init(){
		//doprintln(view," **************************************** ");
		doprintln(view," RunTimeKb INIT ");
		doprintln(view," ------------------------------------------------- ");				
	}

	public static void setDistributed(){
		isDistributed = true;
	}
	
	public static boolean isDistributed(){
		return isDistributed ;
	}
	
	public static void addInputConnMsg(String msgId, boolean withAnswer) {
		inputConnMsg.put(msgId, new Boolean( withAnswer ) );
	}
	
	public static Boolean getInputConnMsg(String msgId ) {
		Boolean ba = inputConnMsg.get( msgId );
		if( ba == null ) return new Boolean(false);
 			return ba  ;	//if null it does not exist
 	}
 	
	public static boolean worksWith(String protocol, String subjName, String msgId){
		return false;
 	}

	public static boolean worksWithConnProtocol( String subjName, String msgId){
		return false;
 	}

/*
* UTILS	
*/	
	
	protected static void println(IOutputView view, String msg){
		if( ! debug ) return ;
		String m = "    %%% RunTimeKb "+ msg ;
		doprintln(view,m);		
	}

	protected static void doprintln(IOutputView view, String m){
		if( view != null )
			view.addOutput(m);
		else System.out.println(m);		
	}	
}
