<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="messages"
    nsURI="http:///it/unibo/droneMission/interfaces/messages.ecore" nsPrefix="it.unibo.droneMission.interfaces.messages">
  <eClassifiers xsi:type="ecore:EClass" name="ICommand" eSuperTypes="#//IMessage">
    <eOperations name="hasValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="setValue">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFile" eSuperTypes="#//IMessage">
    <eOperations name="setName">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setCreationTime">
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="setLastModificationTime">
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="setData">
      <eParameters name="file" eType="#//InputStream"/>
    </eOperations>
    <eOperations name="setData">
      <eParameters name="base64" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModificationTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="#//InputStream"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAsBase64" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMessage">
    <eOperations name="toJSON" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INotify" eSuperTypes="#//IMessage">
    <eOperations name="setMessage">
      <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISensorsData" eSuperTypes="#//IMessage">
    <eOperations name="addGauge">
      <eParameters name="gauge" eType="ecore:EClass gauges.ecore#//IGauge"/>
    </eOperations>
    <eOperations name="removeGauge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="gauge" eType="ecore:EClass gauges.ecore#//IGauge"/>
    </eOperations>
    <eOperations name="hasGauge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="gauge" eType="ecore:EClass gauges.ecore#//IGauge"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gauges" upperBound="-1"
        eType="ecore:EClass gauges.ecore#//IGauge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypesCommand">
    <eLiterals name="REPLY_OK"/>
    <eLiterals name="REPLY_NO" value="-1"/>
    <eLiterals name="REPLY_FAIL" value="-2"/>
    <eLiterals name="START_MISSION" value="1"/>
    <eLiterals name="END_MISSION" value="2"/>
    <eLiterals name="SPEED_SET" value="3"/>
    <eLiterals name="SPEED_INCREASE" value="4"/>
    <eLiterals name="SPEED_DECREASE" value="5"/>
    <eLiterals name="PICTURES_DELAY" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypesNotify">
    <eLiterals name="START_MISSION"/>
    <eLiterals name="END_MISSION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="InputStream" instanceClassName="java.io.InputStream"/>
</ecore:EPackage>
