/*
*  Generated by AN Unibo
*/
package it.unibo.contact.DroneMissionSystem;
//Import generated by the contact spec
//Other Import
import it.unibo.contact.platformuv.*;
import it.unibo.is.interfaces.*;
import it.unibo.is.interfaces.platforms.*;
//import org.eclipse.xtext.xbase.lib.*;
//import org.eclipse.xtext.xbase.lib.Functions.*;
import java.util.Vector;
import it.unibo.contact.platformuv.LindaLike;
import it.unibo.is.interfaces.protocols.IConnInteraction;
//import java.awt.Color;
//For Xbase code 
import org.eclipse.xtext.xbase.lib.Functions.*;
import org.eclipse.xtext.xbase.lib.*;

public abstract class HeadQuarterSupport extends Subject{
	private static HeadQuarter obj = null;
	/*
	* Factory method: returns a singleton
	*/
	public static HeadQuarter create() throws Exception{
		if( obj == null ) obj = new HeadQuarter();
		return obj;
	}
	/* -------------------------------------
	* Local state of the subject
	* --------------------------------------
	*/
	protected int lastMsgNum = 0;
	
	
	//Constructor
	public HeadQuarterSupport() throws Exception{
		super();
	 	isMultiInput=true;
	 	inputMessageList=new String[]{"dataSensor","photo", "endSelectInput"};
		//Singleton
		if( obj != null ) return;
	//	initLastMsgRdMemo();  //put in initGui since the name must be set
		 obj = (HeadQuarter)this;
	}
	
	/* -------------------------------------
	* Init
	* --------------------------------------
	*/
	//PREPARE INPUT THREADS
	public void initInputSupports() throws Exception{
	PlatformExpert.findInSupport( getName(), "photo" ,false,view);
	}
	
 	protected void initLastMsgRdMemo(){
 			lastMsgRdMemo.put("dataSensor"+getName(),0);
 			lastMsgRdMemo.put("photo"+getName(),0);
 	}
	protected void initGui(){
		if( env != null ) view = env.getOutputView();
	    initLastMsgRdMemo(); //put here since the name must be set
	}
	
	/* -------------------------------------
	* State-based Behavior
	* -------------------------------------- 
	*/ 
   	
 	/* -------------------------------------
	* COMMUNICATION CORE OPERATIONS for HeadQuarter
	* --------------------------------------
	*/
 
	protected IMessage hl_HeadQuarter_serve_photo(   ) throws Exception {
	IMessage m = new Message("HeadQuarter_photo(ANY,photo,M,N)");
	IMessage inMsg = comSup.inOnly( getName() ,"photo", m );
	
		return inMsg;
	
	}
	
	protected IMessage hl_HeadQuarter_sense_dataSensor(   ) throws Exception {
	IMessage m = new Message("dataSensor(ANY,dataSensor,M,N)");
	IMessage inMsg = comSup.rdw( getName() ,"dataSensor",  lastMsgRdMemo,m );
		return inMsg;
	
	}
	protected IMessage hl_HeadQuarter_sense_dataSensor( boolean mostRecent  ) throws Exception {
	if( ! mostRecent) return hl_HeadQuarter_sense_dataSensor ();
	else{
	IMessage m = new Message("dataSensor(ANY,dataSensor,M,N)");
	IMessage inMsg = comSup.rdwMostRecent(getName() ,"dataSensor",  lastMsgRdMemo,m );
		return inMsg;
	}
	
	}
	
	protected IAcquireOneReply hl_HeadQuarter_ask_command_Drone( String M  ) throws Exception {
	//EXPERT for COMPOSED HeadQuarter_ask_command_Drone isInput=false withAnswer=true applVisible=true
	M = MsgUtil.putInEnvelope(M);
	IAcquireOneReply answer = comSup.outIn(
	"Drone","command",getName(), 
	"Drone_command("+getName()+",command,"+M+","+msgNum+")","HeadQuarter_Drone_command(Drone,command,M,"+msgNum+")" ); 
	msgNum++;return answer;
	
	}
	
	
 	/* -------------------------------------
	* CONNECTION OPERATIONS for HeadQuarter
	* --------------------------------------
	*/
	
	/* -------------------------------------
	* Local body of the subject
	* --------------------------------------
	*/
	
	public abstract void doJob() throws Exception;
	
	protected IMessage acquire(String msgId) throws Exception{
	  //showMsg("acquire "  +  msgId ); 
	  IMessage m;
	  //USER MESSAGES
	  if( msgId.equals("photo")){
	  	m = hl_HeadQuarter_serve_photo();
	  	return m;
	  }
	 if( msgId.equals("endSelectInput")){
	  String ms = MsgUtil.bm(MsgUtil.channelInWithPolicy(InteractPolicy.nopolicy(),getName(), "endSelectInput"), 
	    getName(), "endSelectInput", "ANY", "N");
	  //Serve the auto-dispatch
	  IMessage min = core.in(new Message(ms).toString());
	  return min;
	 }
	  throw new Exception("Wrong msgId:"+  msgId);
	}//acquire	
	
	/* -------------------------------------
	* Operations (from Java)
	* --------------------------------------
	*/
	//Variable subject declarations
	
		
	/* -------------------------------------
	* Termination
	* --------------------------------------
	*/
	public void terminate() throws Exception{ //by EndSubjectConnections
		HeadQuarterAsk_command_DroneEnd();HeadQuarterServe_photoEnd();
	 			 //Auto-forward a dispatch to finish selectInput operations
	 		    String ms =
	 		      MsgUtil.bm(MsgUtil.channelInWithPolicy(InteractPolicy.nopolicy(),getName(), "endSelectInput"), 
	 		       getName(), "endSelectInput", "endSelectInput", "0");
	 		    core.out(ms);
	}
	
	// Teminate operations
	protected void HeadQuarterAsk_command_DroneEnd() throws Exception{
	 		PlatformExpert.findOutSupportToEnd("HeadQuarter","command",getName(),view );
		showMsg("terminate HeadQuarterAsk_command_Drone");
	}	
	protected void HeadQuarterServe_photoEnd() throws Exception{
	 		PlatformExpert.findInSupportToEnd(getName(),"photo",view );
		showMsg("terminate HeadQuarterServe_photo");
	}
}//HeadQuarterSupport
